### ISSUE TITLE
Match the NIST controls and CCI to the low/moderate/high listing to only return valid controls

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-api-compliance#2]
https://nvd.nist.gov/800-53/Rev4/impact/low

Based on the different listings for low, moderate, and high only return the valid controls that correspond to what the system is referenced as.

Note: need to add that selection to a system to show low/moderate/high. That may mean a System record collection and a unique ID for system (no spaces, only letters and dashes)

**Comment by DaleBingham** [comment]
There needs to be a hierarchy of low moderate and high. The control that you get back from the API has the level in it. So it may be we have to modify the controls API to only return back controls based on low moderate or high. And then from that listing match on vulnerabilities.

**Comment by Cingulara** [comment]
Fixed in 0.8
